jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    container:
      image: atlassian/forge-devcontainer:latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Deploy and upgrade install (staging)
        uses: wjkennedy/a9-forge-ci@v1
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        with:
          working-directory: "."
          usage-analytics: "true"
          environment: "staging"
          pre-run: |
            npm ci
          deploy: "true"
          install: "true"
          site: ${{ vars.ATLASSIAN_SITE }}
          product: ${{ vars.ATLASSIAN_PRODUCT }}
          upgrade: "true"
          confirm-scopes: "true"
